### ISSUE TITLE
`send` callback called twice?

### ISSUE THREAD

**Issue by wearhere** [andris9/nodemailer-smtp-pool#10]
In the wake of [this change](https://github.com/andris9/nodemailer-smtp-pool/commit/3e7a431e9f2e015c01f1ca0b01230c5a972377c7), if the connection emits an error, would `connection.send`'s callback still be called? And `element.callback` so called twice? That seems like a bug.

I'm not sure how to prompt the connection to emit an error but we're seeing evidence of the callback being called twice on our side.

**Comment by andris9** [comment]
Added check to limit callback invocations to 1 a886ca78b6587dfb45e7f431c6e41b5f1d2bcedd. Published as v1.1.3

**Comment by wearhere** [comment]
Thanks for the speedy response @andris9 !
