### ISSUE TITLE
Any full example for using smtp pool

### ISSUE THREAD

**Issue by anshulguleria** [andris9/nodemailer-smtp-pool#11]
Can we have full code example for smtp pool usage. Current examples only include creation of transport. But how do we send mail?

**Comment by andris9** [comment]
See Nodemailer examples [here](https://github.com/andris9/Nodemailer/blob/master/examples/full.js).

**Comment by anshulguleria** [comment]
@andris9 Those are examples for nodemailer but I was more focused on using smpt-pool with nodemailer can I get an example on that?

**Comment by andris9** [comment]
Take the linked Nodemailer example and replace `createTransport` block with the code from this README and thats it

**Comment by andris9** [comment]
See this example: https://gist.github.com/andris9/411857993e8935c77c48
