### ISSUE TITLE
Something is wrong in the tests

### ISSUE THREAD

**Issue by satazor** [andris9/nodemailer-smtp-pool#13]
I've found a bug in `nodemailer-smtp-pool` and I would like to do a PR.
I was adding a test to replicate the bug that I found but there are strange things going on:

```js
        server.on('startData', function(connection) {
            connection.chunks = [];
        });

        server.on('data', function(connection, chunk) {
            connection.chunks.push(chunk);
        });

        server.on('dataReady', function(connection, callback) {
            var body = Buffer.concat(connection.chunks);
            expect(body.toString()).to.equal(message.trim().replace(/\n/g, '\r\n'));
            callback(null, true);
        });
```

The events above are never fired by the server, and looking at `node-smtp-server` those events are not being emitted there. This means that the assertions being done in those listeners are never executed. Am I missing something?

**Comment by andris9** [comment]
Yes, you're right. I replaced the smtp server module but forgot to rewrite the tests. I just updated data stream handling, so the latest commit should handle it correctly https://github.com/andris9/nodemailer-smtp-pool/commit/bd4b4268fbdb8c63c90d5753b0aa6f2762c2bf8d?w=1
