### ISSUE TITLE
Race conditions that cause the pool.send callback to never be called

### ISSUE THREAD

**Issue by satazor** [andris9/nodemailer-smtp-pool#14]
# First problem

The first problem is around a single instance of `smtp-connection`. Take into the consideration this flow of events:

1 - `this._socket` emits `connect`
2 - `_onConnect` is executed and `end` & `close` listeners are added
3 - Server tells you to upgrade the connection to be secure and `_upgradeConnection` is executed
4 - a new `this._socket` is created but `end` & `close` events are not added to this new instance

This means that an idle socket that is closed remotely does not trigger the `_onClose` and `_onEnd` callback function which causes problems on the `nodemailer-smtp-pool`. Head on to the second problem.

# Second problem

As describe above, one or more connections allocated by the pool might already be closed but the pool never gets notified of that. This means that when calling `pool.send()`, there's a chance that a closed connection will be used to send the email, which causes a `close` event to be emitted on the connection right after calling this method: https://github.com/andris9/nodemailer-smtp-pool/blob/master/src/smtp-pool.js#L158 

Because that code doesn't handle the `close`/`end` event, the message will never be reassigned and therefore the callback passed to `pool.send()` will never be called.

While this bug is a consequence of the first one, it still should be handled because the connection might be terminated spontaneously right after.

I will add tests for the bugs described here and propose PRs for these changes if thats ok for you?
Hope that I was explicit in my explanation. Feel free to ask anything otherwise.

Thanks

**Comment by tnunes** [comment]
:+1:

**Comment by marcooliveira** [comment]
:+1:

**Comment by andris9** [comment]
I added close and end events to smtp-connection (https://github.com/andris9/smtp-connection/commit/9677c39fb42af9d54e2de9bedfc07ae09bd72a8e?w=1). If you have any additional tests/fixes you'd like to add, then feel free to make a PR.

**Comment by satazor** [comment]
Thanks for addressing this.

Shouldn't we remove the `close`, `end` & `timeout` events also here (just in case...)? Can't we simply do `removeAllListeners`?
https://github.com/andris9/smtp-connection/commit/9677c39fb42af9d54e2de9bedfc07ae09bd72a8e#diff-3f54aaa87cd2e1c43e57bb854e2a0be7R456

**Comment by satazor** [comment]
I've added a PR to include a failing test that replicates the second problem. Note that the issue still exists with the recent fix on the smtp-connection because I'm simulating the socket being closed right after calling `send()`. I will submit another PR with the fix.

**Comment by satazor** [comment]
Please do not merge anything yet, I'm having problems getting the tests right on Travis. Tests are ok on my Mac though.

**Comment by satazor** [comment]
All good now, #17 contains the failing test and #18 contains the fix. These two PR solve the second problem. The first one was fixed with your [commit](https://github.com/andris9/smtp-connection/commit/9677c39fb42af9d54e2de9bedfc07ae09bd72a8e?w=1) to smtp-connection

I'm not particularly happy with the code in #18, feel free to change it if necessary.

**Comment by satazor** [comment]
Thanks for merging my fix, can you please release a new version soon? :)

**Comment by andris9** [comment]
I updated the code a bit. You're right, the callback harness was not needed anymore, so I re-removed it. Additionally I wanted to use already existing onError and onClose callbacks instead of setting and removing new ones for every send action. The changes can be seen here: https://github.com/andris9/nodemailer-smtp-pool/commit/2e5da27fc867ee52536a8dfca8b63c3e9cdd8203 If you have no objections about the change (maybe i missed something) then I'll publish it to npm today or tomorrow

**Comment by satazor** [comment]
I didn't like my original solution, it was pretty much a "hack" and I didn't want to change a lot of code. Not it makes more sense with your changes! They look good.

**Comment by andris9** [comment]
Publisehd as [v1.1.6](https://www.npmjs.com/package/nodemailer-smtp-pool)

**Comment by satazor** [comment]
@andris9 Thanks for getting this fixed so fast! <3
