### ISSUE TITLE
getaddrinfo EMFILE

### ISSUE THREAD

**Issue by klimashkin** [andris9/nodemailer-smtp-pool#5]
Strange, but sometimes i'm getting error ```sendMail``` method's callback

```
{ [Error: getaddrinfo EMFILE] code: 'EMFILE', errno: 'EMFILE', syscall: 'getaddrinfo' }
Error: getaddrinfo EMFILE
    at errnoException (dns.js:37:11)
    at Object.onanswer [as oncomplete] (dns.js:124:16) undefined
```

**Comment by andris9** [comment]
EMFILE indicates that you have run out of file descriptors, you should either set a higher fd limit or retry the sending after some back-off time as the problem should disappear after previous file descriptors have been closed.

**Comment by klimashkin** [comment]
Thanks for explanations!
