### ISSUE TITLE
how long the pool can remain

### ISSUE THREAD

**Issue by simonchan2013** [andris9/nodemailer-smtp-pool#6]
excuse me, if i create a pool when i start my project, and then wait for a task to send mails(maybe once a day), and the other time this pool will do nothing, and i want to know if the pool will auto close when it is free, and can i set it always active? thanks

**Comment by andris9** [comment]
The pool creates connections lazily, which means that if there are no available connections when sending mail and connection count is not reached yet, a new connection is created. Once the mail is sent the connection is kept open until the server closes it for timeout. Normally this means that all connections are closed after a few minutes of idle time.
